"""Every documentation link a package has, not just the best one.

The earlier workbook picked a single best_doc_url per package. That is what
you want when sending someone to the docs, but it hides the rest: a gem can
have a hand-written site *and* a rubydoc.info page *and* a README *and* a
docs/ folder, and which of those is useful depends on what you are doing.

So this puts every link in its own column, grouped by what kind of thing it
is, because they are not equivalent:

  hand-written      a real documentation site somebody wrote and maintains
  tool-generated    rubydoc.info / rdoc.info for Ruby. Generated by running
                    YARD over the gem's own source, so the page exists whether
                    or not a single comment was written -- 647 gems have one
                    of these and 0% documented methods
  inside-package    README, docs/ folder, or the compiler-emitted XML file in
                    a .nupkg. Content that exists by definition and needs no
                    scraping
  repository        GitHub docs folder, wiki, Pages site, homepage
  registry          the rubygems.org / nuget.org page

`doc_types_available` lists which kinds a package actually has, and
`link_count` how many distinct links there are. A package with a
tool-generated link and nothing else is documented on paper only.

Writes <lang>/step-5-documentation/all-documentation-links.xlsx
"""
from __future__ import annotations

import os
import sys

import pandas as pd

from census.core import OUT_DIR

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir,
                    "Third_party_packages")
SRC = os.path.join(OUT_DIR, "third_party_method_count_latest")
FINAL = os.path.join(OUT_DIR, "final")
S5 = "documentation"
AUTOGEN = ("rubydoc.info", "rdoc.info")
HDR = {"bold": True, "bg_color": "#1f3a5f", "font_color": "white", "border": 1}

COLS = [
    "package", "version", "downloads",
    "doc_types_available", "link_count",
    "handwritten_site", "tool_generated_docs",
    "readme_in_package", "docs_folder_in_package", "docs_folder_files",
    "xml_docs_in_package",
    "github_repo", "github_docs_folder", "github_wiki", "github_pages",
    "homepage", "changelog", "registry_page",
    "doc_coverage_pct",
]


def _u(v):
    """A usable URL, or empty. NaN is a float and floats are truthy in Python,
    so a plain `a or b` would silently pass NaN through."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return ""
    v = str(v).strip()
    return "" if v.lower() in ("nan", "none") else v


def ruby():
    u = pd.read_csv(os.path.join(FINAL, "3_union", "ruby_union.csv"))
    names = u["registry_name"].fillna(u["package"]).astype(str)
    keep = set(names.str.lower())

    api = pd.read_csv(os.path.join(SRC, "ruby_api_v2_versions.csv"),
                      low_memory=False)
    api = api[api.status == "ok"][["gem", "version"]]
    api = api[api.gem.astype(str).str.lower().isin(keep)].drop_duplicates("gem")

    pg = pd.read_csv(os.path.join(OUT_DIR, "ruby_pages.csv"), low_memory=False,
                     usecols=["gem", "link_docs", "link_home", "link_changelog",
                              "link_wiki", "link_code", "link_bugs"])
    pg = pg.drop_duplicates("gem")
    d = api.merge(pg, on="gem", how="left")

    links = os.path.join(SRC, "ruby_doc_links.xlsx")
    if os.path.exists(links):
        t = pd.read_excel(links, "all_gems")
        cols = [c for c in ("gem", "gh_docs_dir", "gh_has_wiki", "gh_has_pages",
                            "gh_homepage", "doc_coverage_pct", "github_url",
                            "readme", "doc_dir_files") if c in t.columns]
        d = d.merge(t[cols].drop_duplicates("gem"), on="gem", how="left")

    inv = os.path.join(FINAL, "7_inventory", "ruby_inventory.csv")
    if os.path.exists(inv):
        iv = pd.read_csv(inv, low_memory=False,
                         usecols=["package", "readme_file", "docs_folder_files",
                                  "docs_folder_count", "downloads"])
        iv = iv.rename(columns={"package": "gem"}).drop_duplicates("gem")
        d = d.merge(iv, on="gem", how="left")

    rows = []
    for r in d.itertuples():
        gh = _u(getattr(r, "github_url", ""))
        docs = _u(getattr(r, "link_docs", ""))
        auto = docs if any(h in docs.lower() for h in AUTOGEN) else ""
        hand = "" if auto else docs
        home = _u(getattr(r, "link_home", ""))
        if not hand and home and not any(
                h in home.lower() for h in
                ("github.com", "gitlab.com", "rubygems.org", "bitbucket.org")):
            hand = home
        cov = getattr(r, "doc_coverage_pct", None)
        if not auto and pd.notna(cov) and cov and float(cov) > 0:
            auto = "https://rubydoc.info/gems/" + str(r.gem)
        readme = _u(getattr(r, "readme_file", ""))
        ddir = getattr(r, "docs_folder_count", 0)
        ddir = 0 if pd.isna(ddir) else int(ddir)
        ghdocs = _u(getattr(r, "gh_docs_dir", ""))
        rows.append({
            "package": r.gem, "version": r.version,
            "downloads": getattr(r, "downloads", None),
            "handwritten_site": hand,
            "tool_generated_docs": auto,
            "readme_in_package": readme,
            "docs_folder_in_package": "Yes" if ddir else "",
            "docs_folder_files": _u(getattr(r, "docs_folder_files", ""))[:400],
            "xml_docs_in_package": "",
            "github_repo": gh,
            "github_docs_folder": (gh + "/tree/HEAD/" + ghdocs) if (gh and ghdocs) else "",
            "github_wiki": (gh + "/wiki") if (gh and getattr(r, "gh_has_wiki", False)) else "",
            "github_pages": _u(getattr(r, "gh_homepage", "")) if getattr(r, "gh_has_pages", False) else "",
            "homepage": home,
            "changelog": _u(getattr(r, "link_changelog", "")),
            "registry_page": "https://rubygems.org/gems/" + str(r.gem),
            "doc_coverage_pct": cov,
        })
    return pd.DataFrame(rows)


def csharp():
    u = pd.read_csv(os.path.join(FINAL, "3_union", "csharp_union.csv"))
    keep = set(u["registry_name"].fillna(u["package"]).astype(str).str.lower())

    d = pd.read_csv(os.path.join(SRC, "_nuget_docs_scan.csv"), low_memory=False)
    d = d[(d.status == "ok")
          & d.package.astype(str).str.lower().isin(keep)].copy()

    pg = pd.read_csv(os.path.join(OUT_DIR, "nuget_pages.csv"), low_memory=False,
                     usecols=["package", "project_url", "repository_url"])
    d = d.merge(pg.drop_duplicates("package"), on="package", how="left")

    fr = pd.read_csv(os.path.join(OUT_DIR, "frame_nuget.csv"), low_memory=False,
                     usecols=["name", "downloads", "repo_owner", "repo_name"])
    fr["package"] = fr["name"]
    d = d.merge(fr.drop_duplicates("package")[["package", "downloads",
                                               "repo_owner", "repo_name"]],
                on="package", how="left")

    rows = []
    for r in d.itertuples():
        gh = ("https://github.com/" + str(r.repo_owner) + "/" + str(r.repo_name)
              if pd.notna(r.repo_owner) and pd.notna(r.repo_name) else "")
        proj = _u(r.project_url)
        # a project_url pointing at the repo or the registry is not a doc site
        hand = "" if (not proj or any(h in proj.lower() for h in
                                      ("github.com", "nuget.org",
                                       "gitlab.com"))) else proj
        rows.append({
            "package": r.package, "version": r.version,
            "downloads": getattr(r, "downloads", None),
            "handwritten_site": hand,
            "tool_generated_docs": "",   # NuGet has no rubydoc.info equivalent
            "readme_in_package": _u(r.readme),
            "docs_folder_in_package": "",
            "docs_folder_files": "",
            "xml_docs_in_package": _u(r.xml_doc),
            "github_repo": gh,
            "github_docs_folder": "", "github_wiki": "", "github_pages": "",
            "homepage": proj,
            "changelog": "",
            "registry_page": "https://www.nuget.org/packages/" + str(r.package),
            "doc_coverage_pct": None,
        })
    return pd.DataFrame(rows)


KINDS = [("handwritten_site", "hand-written site"),
         ("tool_generated_docs", "tool-generated"),
         ("readme_in_package", "readme"),
         ("docs_folder_in_package", "docs folder"),
         ("xml_docs_in_package", "xml docs"),
         ("github_docs_folder", "github docs"),
         ("github_wiki", "github wiki"),
         ("github_pages", "github pages"),
         ("homepage", "homepage")]


def finish(t):
    def kinds(r):
        return "; ".join(label for col, label in KINDS if _u(r.get(col)))
    t["doc_types_available"] = t.apply(kinds, axis=1)
    t["link_count"] = t.apply(
        lambda r: sum(1 for c in
                      ("handwritten_site", "tool_generated_docs",
                       "github_docs_folder", "github_wiki", "github_pages",
                       "homepage", "changelog") if _u(r.get(c))), axis=1)
    return t[COLS].sort_values("downloads", ascending=False,
                               na_position="last")


def summary(t, label):
    n = len(t)

    def cnt(c):
        return int((t[c].fillna("").astype(str).str.strip() != "").sum())
    rows = [(label, "", ""), ("  packages", n, "")]
    for col, name in KINDS:
        c = cnt(col)
        if c:
            rows.append(("  " + name, c, str(round(100 * c / n, 1)) + "%"))
    only_auto = int(((t.tool_generated_docs.fillna("") != "")
                     & (t.handwritten_site.fillna("") == "")
                     & (t.readme_in_package.fillna("") == "")).sum())
    if only_auto:
        rows.append(("  tool-generated and nothing else", only_auto,
                     "a page exists; nobody wrote it"))
    rows.append(("  no link of any kind", int((t.link_count == 0).sum()), ""))
    rows.append(("", "", ""))
    return rows


def main():
    out = {}
    for lang, fn in (("ruby", ruby), ("csharp", csharp)):
        t = finish(fn())
        out[lang] = t
        path = os.path.join(ROOT, lang, S5, "documentation-sources.xlsx")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        sheets = {
            "summary": pd.DataFrame(summary(t, lang.upper()),
                                    columns=["metric", "value", "note"]),
            "all_links": t,
            "handwritten_sites": t[t.handwritten_site != ""],
            "no_links_at_all": t[t.link_count == 0],
        }
        if lang == "ruby":
            sheets["tool_generated_only"] = t[
                (t.tool_generated_docs != "") & (t.handwritten_site == "")
                & (t.readme_in_package == "")]
        try:
            w = pd.ExcelWriter(path, engine="xlsxwriter")
        except Exception:
            path = path.replace(".xlsx", "_live.xlsx")
            w = pd.ExcelWriter(path, engine="xlsxwriter")
        with w:
            hdr = w.book.add_format(HDR)
            num = w.book.add_format({"num_format": "#,##0"})
            for nm, s in sheets.items():
                s.to_excel(w, sheet_name=nm[:31], index=False)
                ws = w.sheets[nm[:31]]
                ws.freeze_panes(1, 1)
                ws.autofilter(0, 0, max(len(s), 1), max(len(s.columns) - 1, 0))
                for i, c in enumerate(s.columns):
                    wide = any(k in str(c) for k in
                               ("url", "site", "docs", "github", "homepage",
                                "changelog", "page", "readme", "types",
                                "metric", "note"))
                    ws.set_column(i, i, 46 if wide else 16,
                                  num if str(c) in ("downloads", "value")
                                  else None)
                    ws.write(0, i, str(c), hdr)
        print(lang, "->", os.path.basename(path), len(t), "packages")
        for m, v, note in summary(t, lang.upper()):
            if m.strip():
                print("   ", m.strip(), v, note)
    return 0


if __name__ == "__main__":
    sys.exit(main())
