"""What documentation each gem actually has -- declared links, shipped files,
and the share of its methods that carry a doc comment.

The three are separate questions and answering only the first is misleading.
1,476 gems name rubydoc.info as their documentation URL, but that site is
generated by running YARD over the gem's own source: the page exists whether
or not anyone wrote a word. Measured over cached gems, only 28.9% of methods
carry a doc comment and 15% of gems have none at all -- so a documentation
link is not evidence of documentation.

Hence three groups of columns:

  declared    the URLs the gem publishes (doc, home, changelog, wiki, bugs),
              with doc_is_autogen marking the ones that merely point at a
              generated site.
  shipped     README / CHANGELOG / LICENSE / guides actually inside the .gem.
              This is narrative documentation and it either exists or it does
              not -- nothing auto-generates it.
  written     methods_documented / methods_total, from a tree-sitter pass. A
              doc comment is a run of comment nodes ending on the line
              immediately above a def.

Reads the gem cache, so it needs no network.

Writes out/third_party_method_count_latest/ruby_documentation.xlsx
"""
from __future__ import annotations

import gzip
import io
import os
import re
import sys
import tarfile
from concurrent.futures import ProcessPoolExecutor
from urllib.parse import urlparse

import pandas as pd

from census.core import OUT_DIR

DIR = os.path.join(OUT_DIR, "third_party_method_count_latest")
CACHE = os.path.join(DIR, "_gem_cache")
AUTOGEN = {"rubydoc.info", "rdoc.info", "www.rubydoc.info"}
README = re.compile(r"^(?:[^/]+/)?readme", re.I)
CHANGE = re.compile(r"^(?:[^/]+/)?(changelog|changes|history|news)", re.I)
LICENSE = re.compile(r"^(?:[^/]+/)?(licen[cs]e|copying)", re.I)
DOCDIR = re.compile(r"(^|/)(docs?|documentation|guides?|manual)/", re.I)
DOCEXT = (".md", ".rdoc", ".txt", ".rst", ".adoc")
LINKS = ["link_docs", "link_home", "link_changelog", "link_wiki",
         "link_code", "link_bugs"]


def scan(path):
    """(doc-file facts, doc-comment coverage) for one cached .gem."""
    import tree_sitter_ruby as tsr
    from tree_sitter import Language, Parser
    parser = Parser(Language(tsr.language()))

    name = os.path.basename(path)[:-4]
    out = dict(stem=name, readme="", readme_bytes=0, has_changelog=False,
               has_license=False, doc_dir_files=0, doc_files=0,
               methods_total=0, methods_documented=0)
    try:
        with open(path, "rb") as fh:
            raw = fh.read()
        with tarfile.open(fileobj=io.BytesIO(raw)) as outer:
            payload = gzip.decompress(outer.extractfile("data.tar.gz").read())
    except Exception:
        return out

    def walk(node, src):
        prev = None
        for ch in node.children:
            if ch.type == "comment":
                prev = ch
                continue
            if ch.type in ("method", "singleton_method"):
                out["methods_total"] += 1
                # a doc comment is the comment run ending on the line above
                if prev is not None and prev.end_point[0] + 1 == ch.start_point[0]:
                    out["methods_documented"] += 1
                prev = None
                walk(ch, src)
                continue
            prev = None
            walk(ch, src)

    try:
        with tarfile.open(fileobj=io.BytesIO(payload)) as inner:
            for mem in inner.getmembers():
                if not mem.isfile():
                    continue
                n = mem.name
                low = n.lower()
                if README.match(n) and not out["readme"]:
                    out["readme"] = n
                    out["readme_bytes"] = mem.size
                elif CHANGE.match(n):
                    out["has_changelog"] = True
                elif LICENSE.match(n):
                    out["has_license"] = True
                if DOCDIR.search(n):
                    out["doc_dir_files"] += 1
                if low.endswith(DOCEXT):
                    out["doc_files"] += 1
                if low.endswith(".rb") and not re.search(r"(^|/)(test|spec)/", low):
                    fh = inner.extractfile(mem)
                    if fh is None:
                        continue
                    src = fh.read()
                    walk(parser.parse(src).root_node, src)
    except Exception:
        pass
    return out


def main():
    # The scan parses every .rb in every gem, so it is cached: iterating on
    # the workbook layout should not mean re-parsing 2,800 packages.
    raw_path = os.path.join(DIR, "_docs_scan.csv")
    if os.path.exists(raw_path):
        d = pd.read_csv(raw_path, low_memory=False)
        print("reusing", len(d), "scanned rows")
    else:
        gems = [os.path.join(CACHE, f) for f in os.listdir(CACHE)
                if f.endswith(".gem")]
        print(len(gems), "cached gems to scan")
        with ProcessPoolExecutor(max_workers=10) as pool:
            rows = list(pool.map(scan, gems, chunksize=8))
        d = pd.DataFrame(rows)
        d.to_csv(raw_path, index=False)

    api = pd.read_csv(os.path.join(DIR, "ruby_api_v2_versions.csv"),
                      low_memory=False)
    api = api[api.status == "ok"][["gem", "version", "functions",
                                   "functions_public"]]
    api["stem"] = api.gem + "-" + api.version.astype(str)
    d = api.merge(d, on="stem", how="left")

    pg = pd.read_csv(os.path.join(OUT_DIR, "ruby_pages.csv"), low_memory=False,
                     usecols=["gem"] + LINKS).drop_duplicates("gem")
    d = d.merge(pg, on="gem", how="left")

    fr = pd.read_csv(os.path.join(OUT_DIR, "frame_ruby.csv"), low_memory=False,
                     usecols=["name", "downloads", "repo_owner", "repo_name"])
    fr["downloads"] = pd.to_numeric(fr["downloads"], errors="coerce")
    d = d.merge(fr, left_on="gem", right_on="name", how="left").drop(columns="name")

    host = d.link_docs.dropna().map(
        lambda u: urlparse(str(u)).netloc.lower().replace("www.", ""))
    d["docs_host"] = host.reindex(d.index)
    d["doc_is_autogen"] = d.docs_host.isin({h.replace("www.", "")
                                            for h in AUTOGEN})
    d["has_readme"] = d.readme.fillna("") != ""
    d["doc_coverage_pct"] = pd.to_numeric(
        100 * d.methods_documented / d.methods_total.replace(0, pd.NA),
        errors="coerce").round(1)
    d["github_url"] = ("https://github.com/" + d.repo_owner.astype(str) + "/"
                       + d.repo_name.astype(str)).where(
                           d.repo_owner.notna() & d.repo_name.notna(), "")
    d = d.sort_values("downloads", ascending=False)

    scanned = d[d.methods_total.notna() & (d.methods_total > 0)]
    summary = pd.DataFrame([
        ("gems in set", len(d), ""),
        ("gems scanned from cache", len(scanned), "rest not cached"),
        ("", "", ""),
        ("--- DECLARED LINKS ---", "", ""),
        ("declare a docs URL", int(d.link_docs.notna().sum()),
         str(round(100 * d.link_docs.notna().mean(), 1)) + "%"),
        ("  of which auto-generated (rubydoc/rdoc.info)",
         int(d.doc_is_autogen.sum()),
         "a page exists whether or not anyone wrote docs"),
        ("  of which a custom doc site",
         int(d.link_docs.notna().sum() - d.doc_is_autogen.sum()), ""),
        ("declare a changelog URL", int(d.link_changelog.notna().sum()), ""),
        ("declare a wiki URL", int(d.link_wiki.notna().sum()), ""),
        ("", "", ""),
        ("--- SHIPPED FILES ---", "", ""),
        ("ship a README", int(scanned.has_readme.sum()),
         str(round(100 * scanned.has_readme.mean(), 1)) + "% of scanned"),
        ("ship a CHANGELOG", int(scanned.has_changelog.sum()), ""),
        ("ship a LICENSE", int(scanned.has_license.sum()), ""),
        ("ship a docs/ or guides/ folder",
         int((scanned.doc_dir_files > 0).sum()), ""),
        ("", "", ""),
        ("--- WRITTEN DOC COMMENTS ---", "", ""),
        ("methods total", int(scanned.methods_total.sum()), ""),
        ("methods with a doc comment", int(scanned.methods_documented.sum()),
         str(round(100 * scanned.methods_documented.sum() /
                   max(scanned.methods_total.sum(), 1), 1)) + "%"),
        ("median per-gem coverage",
         round(float(scanned.doc_coverage_pct.median()), 1), "%"),
        ("gems with 0% documented", int((scanned.doc_coverage_pct == 0).sum()),
         "yet most still publish a docs link"),
        ("gems with >80% documented",
         int((scanned.doc_coverage_pct > 80).sum()), ""),
    ], columns=["metric", "value", "note"])

    cols = ["gem", "version", "downloads", "doc_coverage_pct",
            "methods_documented", "methods_total", "has_readme", "readme",
            "readme_bytes", "has_changelog", "has_license", "doc_dir_files",
            "doc_files", "link_docs", "docs_host", "doc_is_autogen",
            "link_home", "link_changelog", "link_wiki", "link_code",
            "link_bugs", "github_url"]
    detail = d[[c for c in cols if c in d.columns]]

    sheets = {
        "summary": summary,
        "gems": detail,
        "no_docs_at_all": detail[(detail.doc_coverage_pct == 0)
                                 & (~detail.has_readme.fillna(False))],
        "best_documented": detail[detail.methods_total.fillna(0) >= 30]
        .sort_values("doc_coverage_pct", ascending=False).head(300),
        "custom_doc_sites": detail[detail.link_docs.notna()
                                   & (~detail.doc_is_autogen)],
    }
    path = os.path.join(DIR, "ruby_documentation.xlsx")
    try:
        w = pd.ExcelWriter(path, engine="xlsxwriter")
    except Exception:
        path = path.replace(".xlsx", "_live.xlsx")
        w = pd.ExcelWriter(path, engine="xlsxwriter")
    with w:
        hdr = w.book.add_format({"bold": True, "bg_color": "#121a24",
                                 "font_color": "white", "border": 1})
        num = w.book.add_format({"num_format": "#,##0"})
        for nm, t in sheets.items():
            t.to_excel(w, sheet_name=nm, index=False)
            ws = w.sheets[nm]
            ws.freeze_panes(1, 1)
            ws.autofilter(0, 0, max(len(t), 1), max(len(t.columns) - 1, 0))
            for i, c in enumerate(t.columns):
                wide = c in ("metric", "note", "link_docs", "link_home",
                             "link_changelog", "link_code", "link_bugs",
                             "github_url", "readme", "link_wiki")
                ws.set_column(i, i, 42 if wide else 16,
                              num if c in ("downloads", "methods_total",
                                           "methods_documented",
                                           "readme_bytes", "value") else None)
                ws.write(0, i, str(c), hdr)
    print("wrote", path)
    print(summary.to_string(index=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
